apiVersion: v1
kind: ConfigMap
metadata:
  name: envs
data:
  DATABASE_URL: "postgres://postgress:saleor@34.68.85.169/saleor"
  DEFAULT_FROM_EMAIL: "noreply@example.com"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  SECRET_KEY: "changeme"
  AEGER_AGENT_HOST: "jaeger"
  STOREFRONT_URL: "http://localhost:3000/"
  DASHBOARD_URL: "http://localhost:9000/"