{{- if .Values.ingress.enabled -}}
{{- $fullName := include "saleor-chart.fullname" . -}}
{{- $svcPort := .Values.service.ports.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "saleor-chart.labels" . | nindent 4 }}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ $svcPort }}
  {{- end }}